# Generated by Django 5.1.4 on 2024-12-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_relazione_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplan',
            old_name='file_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='effective_year',
        ),
    ]
