# Generated by Django 5.1.4 on 2024-12-16 15:00
# Modified by me

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_rename_file_year_trainingplan_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingPlan',
            new_name='Course',
        ),

        migrations.RenameField(
            model_name='relazione',
            old_name='training_plan',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='relazione',
            unique_together={('course', 'user', 'stato')},
        ),
    ]
