# Generated by Django 5.1.4 on 2024-12-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_course_alter_relazione_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='course_name',
        ),
    ]
