# Generated by Django 5.1.4 on 2024-12-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_rename_relazione_into_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_attendances', to='web_app.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='stato',
            field=models.CharField(choices=[('planned', 'Pianificato'), ('completed', 'Completato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
