# Generated by Django 5.1.4 on 2024-12-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_attendance_options_alter_attendance_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('person', 'Persona'), ('quality_manager', 'Quality Manager')], max_length=20),
        ),
    ]
