# Generated by Django 5.1.4 on 2024-12-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='stato',
            new_name='state',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'user', 'state')},
        ),
    ]
